BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path TO public, extensions;

SELECT plan(14);

CREATE TABLE notification_schema._privilege_probe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM unnest(ARRAY[
      'trip_schema',
      'social_schema',
      'monetization_schema',
      'geo_schema',
      'notification_schema'
    ]) AS expected(schema_name)
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_namespace WHERE nspname = expected.schema_name
    )
  ),
  'all bounded-context schemas exist'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM unnest(ARRAY[
      'trip_service_role',
      'social_service_role',
      'monetization_service_role',
      'geo_service_role',
      'notification_service_role'
    ]) AS expected(role_name)
    WHERE NOT EXISTS (
      SELECT 1 FROM pg_roles WHERE rolname = expected.role_name
    )
  ),
  'all service roles exist'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_roles
    WHERE rolname IN (
      'trip_service_role',
      'social_service_role',
      'monetization_service_role',
      'geo_service_role',
      'notification_service_role'
    )
      AND (
        rolsuper OR rolinherit OR rolcreaterole OR rolcreatedb OR rolcanlogin
        OR rolreplication OR rolbypassrls
      )
  ),
  'service roles have least-privilege attributes'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM (VALUES
      ('trip_schema', 'trip_service_role'),
      ('social_schema', 'social_service_role'),
      ('monetization_schema', 'monetization_service_role'),
      ('geo_schema', 'geo_service_role'),
      ('notification_schema', 'notification_service_role')
    ) AS expected(schema_name, role_name)
    WHERE NOT has_schema_privilege(expected.role_name, expected.schema_name, 'USAGE')
       OR has_schema_privilege(expected.role_name, expected.schema_name, 'CREATE')
  ),
  'each service role can use but cannot create in its schema'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_namespace
    WHERE nspname IN (
      'trip_schema',
      'social_schema',
      'monetization_schema',
      'geo_schema',
      'notification_schema'
    )
      AND has_schema_privilege('public', oid, 'USAGE')
  ),
  'PUBLIC cannot use service schemas'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname IN (
      'trip_schema',
      'social_schema',
      'monetization_schema',
      'geo_schema',
      'notification_schema'
    )
      AND c.relkind IN ('r', 'p')
      AND has_table_privilege('public', c.oid, 'SELECT')
  ),
  'PUBLIC cannot select service tables'
);

SELECT ok(
  has_table_privilege(
    'notification_service_role',
    'notification_schema._privilege_probe',
    'SELECT, INSERT, UPDATE, DELETE'
  )
    AND NOT has_table_privilege(
      'notification_service_role',
      'notification_schema._privilege_probe',
      'TRUNCATE, REFERENCES, TRIGGER'
    ),
  'default table privileges grant only service DML'
);

SELECT ok(
  has_sequence_privilege(
    'notification_service_role',
    'notification_schema._privilege_probe_id_seq',
    'USAGE, SELECT'
  )
    AND NOT has_sequence_privilege(
      'notification_service_role',
      'notification_schema._privilege_probe_id_seq',
      'UPDATE'
    ),
  'default sequence privileges grant usage and select only'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE (
      (n.nspname = 'public' AND p.proname = 'handle_new_user')
      OR (n.nspname = 'trip_schema' AND p.proname LIKE 'is_trip_%')
    )
      AND NOT p.prosecdef
  ),
  'protected helper functions remain security definer'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE (
      (n.nspname = 'public' AND p.proname = 'handle_new_user')
      OR (n.nspname = 'trip_schema' AND p.proname LIKE 'is_trip_%')
    )
      AND NOT (p.proconfig @> ARRAY['search_path=""'])
  ),
  'security-definer functions use an empty fixed search_path'
);

SELECT ok(
  NOT EXISTS (
    SELECT 1
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE (
      (n.nspname = 'public' AND p.proname = 'handle_new_user')
      OR (n.nspname = 'trip_schema' AND p.proname LIKE 'is_trip_%')
    )
      AND has_function_privilege('public', p.oid, 'EXECUTE')
  ),
  'PUBLIC cannot execute protected helper functions'
);

SELECT ok(
  has_function_privilege(
    'authenticated',
    'trip_schema.is_trip_owner(uuid)',
    'EXECUTE'
  ),
  'authenticated can execute the trip owner policy helper'
);

SELECT ok(
  has_function_privilege(
    'authenticated',
    'trip_schema.is_trip_admin(uuid)',
    'EXECUTE'
  ),
  'authenticated can execute the trip admin policy helper'
);

SELECT ok(
  has_function_privilege(
    'authenticated',
    'trip_schema.is_trip_member(uuid)',
    'EXECUTE'
  ),
  'authenticated can execute the trip member policy helper'
);

SELECT * FROM finish();

ROLLBACK;
