"use client";
/* eslint-disable @next/next/no-img-element */

import { Camera, Eye, MapPin, ShieldCheck } from "lucide-react";

const STORIES = [
  { day: "Ngày 1", place: "Cổng Trời Quản Bạ", title: "Check-in giữa biển mây", body: "Sương mù dày đặc nhưng cảnh quan nhìn từ trên cao vẫn rất hùng vĩ.", image: "https://images.unsplash.com/photo-1596700543598-68e37cb0cc2c?w=1000&q=80" },
  { day: "Ngày 2", place: "Đồng Văn", title: "Đêm lửa trại", body: "Một buổi tối chậm rãi, cùng chia sẻ câu chuyện đường dài và món ăn địa phương.", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=1000&q=80" },
] as const;

export default function TripMemoryView() {
  return <main className="min-h-screen bg-background-warm pb-24 text-text-main">
    <header className="relative isolate min-h-[25rem] overflow-hidden bg-secondary px-4 pb-12 pt-28 text-white sm:px-6 sm:pt-36"><div className="absolute inset-0 -z-20 bg-cover bg-center opacity-55" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1541628951107-a55850900b9d?auto=format&fit=crop&w=2200&q=90')" }} /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-secondary via-secondary/50 to-secondary/15" /><div className="page-shell px-0"><p className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-bold backdrop-blur"><Camera size={14} /> Nhật ký hành trình</p><h1 className="mt-5 max-w-3xl text-4xl font-extrabold tracking-tight sm:text-6xl">Mùa vàng Hà Giang</h1><p className="mt-4 text-sm font-medium text-white/80 sm:text-base">350 km · 5 ngày · cùng 5 người bạn</p></div></header>
    <div className="page-shell grid gap-8 px-4 pt-8 sm:px-6 lg:grid-cols-[minmax(0,1fr)_18rem]">
      <section><div className="surface-card flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-primary">Câu chuyện trên đường</p><h2 className="mt-2 text-2xl font-extrabold">Lưu những điều đáng nhớ</h2><p className="mt-2 max-w-xl text-sm leading-6 text-text-sub">Mỗi khoảnh khắc được trình bày theo dòng thời gian để cả nhóm có thể xem lại hành trình một cách riêng tư.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-secondary/10 px-3 py-2 text-xs font-bold text-secondary"><ShieldCheck size={14} /> Chỉ người trong chuyến đi</span></div>
        <div className="relative mt-10 space-y-10 before:absolute before:bottom-0 before:left-4 before:top-0 before:w-px before:bg-border-main sm:before:left-1/2">{STORIES.map((story, index) => <article key={story.day} className={`relative grid gap-5 sm:grid-cols-2 sm:gap-10 ${index % 2 ? "sm:[&>div:first-child]:order-2" : ""}`}><span className="absolute left-4 top-5 z-10 h-3 w-3 -translate-x-1/2 rounded-full border-2 border-surface bg-primary sm:left-1/2" /><div className={`pl-9 sm:pl-0 ${index % 2 ? "sm:text-left" : "sm:text-right"}`}><span className="inline-flex rounded-full bg-secondary px-3 py-1 text-xs font-extrabold text-white">{story.day}</span><div className="mt-3"><p className={`flex items-center gap-1 text-xs font-bold uppercase tracking-[.12em] text-primary ${index % 2 ? "" : "sm:justify-end"}`}><MapPin size={13} /> {story.place}</p><h3 className="mt-2 text-2xl font-extrabold">{story.title}</h3><p className="mt-3 text-sm leading-6 text-text-sub">{story.body}</p></div></div><div className="pl-9 sm:pl-0"><div className="overflow-hidden rounded-[1.5rem] bg-surface shadow-card"><img src={story.image} alt={story.title} className="aspect-[4/3] w-full object-cover" /></div></div></article>)}</div>
      </section>
      <aside className="space-y-5 lg:sticky lg:top-6 lg:h-fit"><section className="surface-card p-6"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-primary">Quyền riêng tư</p><div className="mt-4 flex gap-3"><Eye className="shrink-0 text-secondary" size={20} /><p className="text-sm leading-6 text-text-sub">Album này là bản xem trước UI. Chia sẻ công khai, tải PDF, in sách và chi tiêu nhóm chưa được kết nối trong sản phẩm hiện tại.</p></div></section><section className="surface-card p-6"><h2 className="font-extrabold">Bạn chưa có kỷ niệm?</h2><p className="mt-2 text-sm leading-6 text-text-sub">Khi chuyến đi có nội dung được lưu, timeline sẽ xuất hiện tại đây.</p></section></aside>
    </div>
  </main>;
}
