"use client";
import Link from "next/link";
import { ArrowUpRight, BarChart3, CreditCard, Megaphone, MessageSquare, Store } from "lucide-react";

const areas = [
  { href: "/partner/campaigns", icon: Megaphone, label: "Chiến dịch", description: "Tạo và theo dõi vị trí hiển thị khi module quảng cáo sẵn sàng." },
  { href: "/partner/analytics", icon: BarChart3, label: "Phân tích", description: "Xem hiệu quả và chỉ số khi doanh nghiệp bắt đầu có dữ liệu." },
  { href: "/partner/reviews", icon: MessageSquare, label: "Đánh giá", description: "Theo dõi phản hồi của khách khi review được kích hoạt." },
  { href: "/partner/billing", icon: CreditCard, label: "Thanh toán", description: "Quản lý hoá đơn và phương thức thanh toán khi được kết nối." },
] as const;
export default function PartnerOverviewPanel() { return <main className="min-h-full bg-[#f7f1e8] p-4 sm:p-8"><div className="mx-auto max-w-6xl"><header className="rounded-[2rem] bg-secondary p-7 text-white sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#f2c369]">Partner workspace</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-.04em] sm:text-5xl">Một nơi để chăm sóc<br />hiện diện của bạn.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-white/75">Các công cụ sẽ chỉ hiển thị dữ liệu khi module tương ứng đã được kết nối; không có chỉ số mẫu được dùng làm số liệu thật.</p></header><section className="mt-8"><div className="flex items-end justify-between border-b border-border-main pb-4"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-primary">Không gian làm việc</p><h2 className="mt-2 text-2xl font-extrabold">Bạn muốn làm gì?</h2></div><Store className="text-secondary" /></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{areas.map(({ href, icon: Icon, label, description }) => <Link key={href} href={href} className="group rounded-[1.5rem] border border-border-main bg-surface p-6 shadow-card transition hover:-translate-y-1 hover:shadow-card-hover"><Icon className="text-primary" size={22} /><h3 className="mt-7 flex items-center justify-between text-xl font-extrabold">{label}<ArrowUpRight size={18} className="text-primary transition group-hover:-translate-y-1 group-hover:translate-x-1" /></h3><p className="mt-3 text-sm leading-6 text-text-sub">{description}</p></Link>)}</div></section></div></main>; }
