"use client";
import Link from "next/link";
import { useActionState } from "react";
import { useFormStatus } from "react-dom";
import { ArrowLeft, LoaderCircle, LogIn, Map } from "lucide-react";
import { login, type LoginState } from "@/features/auth/actions";
const initialState: LoginState = { error: null };
const messages = { callback: "Liên kết đăng nhập không hợp lệ hoặc đã hết hạn.", session_expired: "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại." } as const;
function Submit() { const { pending } = useFormStatus(); return <button type="submit" disabled={pending} className="focus-ring mt-2 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-primary px-5 py-3.5 text-sm font-bold text-white shadow-card hover:bg-primary-hover disabled:opacity-60">{pending ? <LoaderCircle size={17} className="animate-spin" /> : <LogIn size={17} />}{pending ? "Đang đăng nhập…" : "Đăng nhập"}</button>; }
export default function LoginView({ authError, nextPath }: { authError?: "callback" | "session_expired"; nextPath?: string }) { const [state, action] = useActionState(login, initialState); return <main className="grid min-h-screen bg-background lg:grid-cols-[minmax(0,1fr)_minmax(28rem,42rem)]"><section className="relative hidden overflow-hidden bg-secondary p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute inset-0 bg-cover bg-center opacity-35" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1541628951107-a55850900b9d?auto=format&fit=crop&w=2000&q=85')" }} /><div className="absolute inset-0 bg-gradient-to-t from-secondary via-secondary/70 to-secondary/30" /><Link href="/" aria-label="Road Trip Vietnam" className="focus-ring relative z-10 inline-flex w-fit items-center gap-2 rounded-lg bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/20"><ArrowLeft size={16} /> Về trang chủ</Link><div className="relative z-10 max-w-xl"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-amber-200">Road Trip Vietnam</p><h1 className="mt-4 text-6xl font-extrabold leading-[.96] tracking-[-.05em]">Đi để thấy<br />nhiều hơn.</h1><p className="mt-6 max-w-md text-lg leading-8 text-white/75">Đăng nhập để lưu hành trình, cùng nhóm xây lịch trình và tiếp tục từ nơi bạn đã dừng lại.</p></div></section><section className="flex items-center px-5 py-10 sm:px-10 lg:px-16"><div className="mx-auto w-full max-w-md"><Link href="/" aria-label="Road Trip Vietnam" className="focus-ring inline-flex items-center gap-2 rounded-lg text-sm font-bold text-text-sub hover:text-text-main lg:hidden"><ArrowLeft size={16} /> Trang chủ</Link><div className="mt-10 flex h-12 w-12 items-center justify-center rounded-xl bg-primary text-white shadow-card"><Map size={22} /></div><h2 className="mt-8 text-4xl font-extrabold tracking-[-.04em]">Chào mừng trở lại!</h2><p className="mt-3 text-sm leading-6 text-text-sub">Đăng nhập để tiếp tục hành trình của bạn.</p><form action={action} className="mt-9 space-y-5">{nextPath && <input type="hidden" name="next" value={nextPath} />}<label className="block text-sm font-bold">Email<input id="email" name="email" type="email" autoComplete="email" required className="field mt-2 bg-surface" placeholder="ban@example.com" /></label><label className="block text-sm font-bold">Mật khẩu<input id="password" name="password" type="password" autoComplete="current-password" minLength={6} required className="field mt-2 bg-surface" placeholder="Ít nhất 6 ký tự" /></label>{(state.error || authError) && <p role="alert" className="rounded-xl bg-danger/10 px-4 py-3 text-sm font-medium text-danger">{state.error ?? (authError && messages[authError])}</p>}<Submit /></form></div></section></main>; }
