"use client";

import { useCallback, useEffect, useState } from "react";
import { changeMemberPermission, createInvitation, listInvitations, listMembers, removeMember, revokeInvitation } from "../api/trips";
import type { Invitation, Member } from "../api/trip-model";

export default function CollaborationPanel({ tripId }: { tripId: string }) {
  const [members, setMembers] = useState<readonly Member[]>([]); const [invitations, setInvitations] = useState<readonly Invitation[]>([]); const [email, setEmail] = useState(""); const [permission, setPermission] = useState<"VIEW" | "EDIT">("VIEW"); const [shareLink, setShareLink] = useState<string>(); const [error, setError] = useState<string>(); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [nextMembers, nextInvitations] = await Promise.all([listMembers(tripId), listInvitations(tripId)]); setMembers(nextMembers); setInvitations(nextInvitations); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể tải cộng tác viên."); } }, [tripId]);
  useEffect(() => { void load(); }, [load]);
  async function invite(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(undefined); try { const invitation = await createInvitation(tripId, email, permission); const link = `${window.location.origin}/trip-invitations/${invitation.token ?? ""}`; setShareLink(link); setEmail(""); await load(); await navigator.clipboard?.writeText(link); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể tạo lời mời."); } finally { setBusy(false); } }
  async function updateMember(userId: string, nextPermission: "VIEW" | "EDIT") { setBusy(true); try { await changeMemberPermission(tripId, userId, nextPermission); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể cập nhật quyền."); } finally { setBusy(false); } }
  async function remove(userId: string) { setBusy(true); try { await removeMember(tripId, userId); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Không thể gỡ thành viên."); } finally { setBusy(false); } }
  return <section className="mt-8 rounded-2xl border border-gray-200 bg-white p-6" aria-labelledby="collaboration-title"><h2 id="collaboration-title" className="text-xl font-bold text-gray-900">Cộng tác viên</h2>{error && <p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}<form onSubmit={(event) => void invite(event)} className="mt-4 flex flex-wrap gap-2"><label className="sr-only" htmlFor="invite-email">Email người được mời</label><input id="invite-email" type="email" required value={email} onChange={(event) => setEmail(event.target.value)} className="field flex-1 bg-white" placeholder="email@example.com"/><select aria-label="Quyền lời mời" value={permission} onChange={(event) => setPermission(event.target.value as "VIEW" | "EDIT")} className="rounded-lg border px-3"><option value="VIEW">Chỉ xem</option><option value="EDIT">Có thể sửa</option></select><button disabled={busy} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Mời</button></form>{shareLink && <div className="mt-3 rounded-lg bg-green-50 p-3 text-sm text-green-900" role="status">Đã tạo lời mời. Liên kết đã được sao chép; bạn cũng có thể <a className="font-bold underline" href={shareLink}>mở liên kết mời</a>.</div>}<ul className="mt-6 space-y-3" aria-label="Thành viên chuyến đi">{members.filter((member) => member.status === "ACTIVE").map((member) => <li key={member.userId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-gray-50 p-3 text-sm"><span><strong>{member.role === "OWNER" ? "Chủ chuyến đi" : "Thành viên"}</strong><span className="ml-2 text-gray-600">{member.userId}</span></span>{member.role === "MEMBER" && <span className="flex gap-2"><select aria-label={`Quyền của ${member.userId}`} disabled={busy} value={member.permission} onChange={(event) => void updateMember(member.userId, event.target.value as "VIEW" | "EDIT")} className="rounded border px-2"><option value="VIEW">Chỉ xem</option><option value="EDIT">Có thể sửa</option></select><button type="button" disabled={busy} onClick={() => void remove(member.userId)} className="rounded border border-red-200 px-2 text-red-700">Gỡ</button></span>}</li>)}</ul>{invitations.length > 0 && <div className="mt-6"><h3 className="font-bold">Lời mời</h3><ul className="mt-2 space-y-2">{invitations.map((invitation) => <li key={invitation.id} className="flex flex-wrap justify-between gap-2 text-sm"><span>{invitation.inviteeEmail} · {invitation.permission} · {invitation.status}</span>{invitation.status === "PENDING" && <button type="button" disabled={busy} onClick={() => void revokeInvitation(tripId, invitation.id).then(load).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Không thể thu hồi lời mời."))} className="font-bold text-red-700 underline">Thu hồi</button>}</li>)}</ul></div>}</section>;
}
