"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, CalendarDays, MapPin, Mountain, Plus, Route, Users } from "lucide-react";
import FeedbackState from "@/components/ui/FeedbackState";
import { GatewayApiError } from "@/features/trip-planning/api/gateway-request";
import { listTrips } from "@/features/trip-planning/api/trips";
import type { TripListItem } from "@/features/trip-planning/api/trip-model";

type State = { kind: "loading" } | { kind: "content"; trips: readonly TripListItem[] } | { kind: "error"; message: string };
const labels: Record<TripListItem["status"], string> = { PLANNING: "Đang chuẩn bị", ONGOING: "Đang trên đường", COMPLETED: "Hoàn tất", CANCELLED: "Đã hủy" };
const formatter = new Intl.DateTimeFormat("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric", timeZone: "UTC" });
const date = (start: string, end: string) => `${formatter.format(new Date(`${start}T00:00:00Z`))} – ${formatter.format(new Date(`${end}T00:00:00Z`))}`;

export default function TripListView() {
  const [state, setState] = useState<State>({ kind: "loading" });
  const load = useCallback(async () => { setState({ kind: "loading" }); try { setState({ kind: "content", trips: await listTrips() }); } catch (error) { setState({ kind: "error", message: error instanceof GatewayApiError ? error.message : "Không thể tải các chuyến đi lúc này." }); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);

  return <main className="min-h-screen bg-background pb-16"><section className="border-b border-border-light bg-surface-container-low"><div className="page-shell px-4 py-10 sm:px-6"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-primary">Chuyến đi của tôi</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-.04em] sm:text-5xl">Sẵn sàng cho chặng tiếp theo.</h1><p className="mt-3 text-text-sub">Tất cả hành trình, ghi chú và người đồng hành của bạn.</p></div><Link href="/trips/new" className="focus-ring inline-flex w-fit items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white shadow-card hover:bg-primary-hover"><Plus size={17} /> Tạo chuyến đi mới</Link></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Overview icon={<Route size={19} />} value="1.480 km" label="Tổng cự ly" /><Overview icon={<Mountain size={19} />} value="14" label="Cung đèo" /><Overview icon={<MapPin size={19} />} value="38" label="Điểm dừng chân" /><Overview icon={<Users size={19} />} value="11" label="Đồng hành" /></div></div></section><section className="page-shell px-4 py-9 sm:px-6"><div className="flex flex-col gap-4 border-b border-border-light pb-5 sm:flex-row sm:items-center sm:justify-between"><h2 className="text-xl font-extrabold">Hành trình của bạn</h2><div className="flex gap-2"><input aria-label="Tìm chuyến đi" placeholder="Tìm chuyến đi" className="field w-full bg-white sm:w-56" /><button type="button" className="focus-ring rounded-lg border border-border-main bg-white px-3 text-sm font-bold text-text-sub">Khởi hành gần nhất</button></div></div>{state.kind === "loading" && <div className="mt-6 grid gap-4 lg:grid-cols-2" aria-busy="true">{[1, 2, 3, 4].map((item) => <div key={item} className="h-64 animate-pulse rounded-panel bg-surface-container-low" />)}</div>}{state.kind === "error" && <div className="mt-8"><FeedbackState kind="error" title="Không tải được hành trình" description={state.message} actionLabel="Thử lại" onAction={load} /></div>}{state.kind === "content" && state.trips.length === 0 && <div className="mt-8"><FeedbackState kind="empty" title="Chuyến đi đầu tiên sẽ bắt đầu ở đây" description="Tạo lịch trình để lưu ngày đi, các điểm dừng và mời người đồng hành."><Link href="/trips/new" className="focus-ring inline-flex rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white">Tạo chuyến đi</Link></FeedbackState></div>}{state.kind === "content" && state.trips.length > 0 && <div className="mt-6 grid gap-5 lg:grid-cols-2">{state.trips.map((trip) => <TripCard key={trip.id} trip={trip} />)}</div>}</section></main>;
}

function Overview({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="rounded-xl bg-white p-4"><div className="text-primary">{icon}</div><p className="mt-3 text-xl font-extrabold">{value}</p><p className="mt-1 text-sm text-text-sub">{label}</p></div>; }
function TripCard({ trip }: { trip: TripListItem }) { const role = trip.role === "OWNER" ? "Chủ hành trình" : trip.permission === "EDIT" ? "Có thể chỉnh sửa" : "Chỉ xem"; return <article className="overflow-hidden rounded-panel border border-border-light bg-white shadow-sm"><div className="h-28 bg-[linear-gradient(130deg,#102A43_0%,#006948_54%,#b67a13_100%)] p-5 text-white"><div className="flex items-start justify-between"><span className="rounded-full bg-white/15 px-2.5 py-1 text-xs font-bold">{labels[trip.status]}</span><span className="inline-flex items-center gap-1 text-xs font-bold"><CalendarDays size={14} /> {date(trip.startDate, trip.endDate)}</span></div></div><div className="p-5"><h3 className="text-xl font-extrabold tracking-[-.02em]">{trip.title}</h3><div className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-surface-container-low p-3 text-xs"><Metric label="Vai trò" value={role} /><Metric label="Điểm dừng" value="Mở planner" /><Metric label="Lịch trình" value={labels[trip.status]} /></div><Link href={`/trips/${trip.id}`} className="focus-ring mt-5 inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline">Mở bản kế hoạch <ArrowRight size={16} /></Link></div></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-text-sub">{label}</p><p className="mt-1 font-bold text-text-main">{value}</p></div>; }
